language: java

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk11
    dist: xenial

cache:
  directories:
  - $HOME/.m2

notifications:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - chmod +x mvnw

before_script:
  - echo MAVEN_OPTS=\"-Xmx2048m -Xms1024m -Djava.awt.headless=true\" > ~/.mavenrc
  - chmod +x mvnw

script: ./mvnw test -DskipTests=false -Pdocker -B

deploy:
  provider: script
  script: "./mvnw deploy -Pdocker -B"
  skip_cleanup: true
  on:
    tags: true